apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: deployment-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: docker.io/brainupgrade/hello:1.0
        name: hello-container
