apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: liveness-container
    image: eu.gcr.io/k8s-artifacts-prod/liveness:latest # updated from google container registry (gcr)
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 1
      successThreshold: 1
      periodSeconds: 10
      
  
