apiVersion: v1
kind: Pod
metadata:
  name: hello2
spec:
  containers:
  - image: docker.io/brainupgrade/hello:1.0
    name: hello2

# apiVersion: v1
# kind:  Pod
# metadata:
#   name: hello3
# spec:
#   containers:
#   - image: docker.io/brainupgrade/hello:1.0
#     name: hello3
    
